# Makefile

# defaults
SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += ../rtl/instruction_memory.v

# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file
TOPLEVEL = instruction_memory

# MODULE is the basename of the Python test file
MODULE = test_instruction_memory

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim
